# Generated by Django 4.0.5 on 2023-05-04 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='课程标题')),
                ('tag', models.CharField(max_length=50, verbose_name='课程标签')),
                ('description', models.TextField(verbose_name='课程描述')),
                ('source', models.CharField(max_length=100, verbose_name='课程来源')),
                ('imgurl', models.URLField(unique=True, verbose_name='图片链接')),
                ('href', models.URLField(unique=True, verbose_name='课程链接')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='truename',
            new_name='realname',
        ),
        migrations.CreateModel(
            name='Course_statistic',
            fields=[
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infor.course')),
                ('avg_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('num_of_collection', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='课程评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infor.course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='用户评论')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.user')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infor.user')),
            ],
        ),
    ]
